package neu.edu.temp;
// Generated Nov 28, 2017 3:48:38 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseRecord generated by hbm2java
 */
@Entity
@Table(name = "purchase_record", catalog = "Info6250Final")
public class PurchaseRecord implements java.io.Serializable {

	private Integer purchaseRecordId;
	private IdeaOption ideaOption;
	private User user;
	private float purchaseRecordnAmount;
	private Date purchaseRecordDate;
	private String purchaseRecordStatus;

	public PurchaseRecord() {
	}

	public PurchaseRecord(IdeaOption ideaOption, User user, float purchaseRecordnAmount, Date purchaseRecordDate,
			String purchaseRecordStatus) {
		this.ideaOption = ideaOption;
		this.user = user;
		this.purchaseRecordnAmount = purchaseRecordnAmount;
		this.purchaseRecordDate = purchaseRecordDate;
		this.purchaseRecordStatus = purchaseRecordStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "purchase_record_id", unique = true, nullable = false)
	public Integer getPurchaseRecordId() {
		return this.purchaseRecordId;
	}

	public void setPurchaseRecordId(Integer purchaseRecordId) {
		this.purchaseRecordId = purchaseRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "option_id", nullable = false)
	public IdeaOption getIdeaOption() {
		return this.ideaOption;
	}

	public void setIdeaOption(IdeaOption ideaOption) {
		this.ideaOption = ideaOption;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "purchase_recordn_amount", nullable = false, precision = 12, scale = 0)
	public float getPurchaseRecordnAmount() {
		return this.purchaseRecordnAmount;
	}

	public void setPurchaseRecordnAmount(float purchaseRecordnAmount) {
		this.purchaseRecordnAmount = purchaseRecordnAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "purchase_record_date", nullable = false, length = 19)
	public Date getPurchaseRecordDate() {
		return this.purchaseRecordDate;
	}

	public void setPurchaseRecordDate(Date purchaseRecordDate) {
		this.purchaseRecordDate = purchaseRecordDate;
	}

	@Column(name = "purchase_record_status", nullable = false, length = 20)
	public String getPurchaseRecordStatus() {
		return this.purchaseRecordStatus;
	}

	public void setPurchaseRecordStatus(String purchaseRecordStatus) {
		this.purchaseRecordStatus = purchaseRecordStatus;
	}

}
