package neu.edu.temp;
// Generated Nov 28, 2017 3:48:38 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShoppingCart generated by hbm2java
 */
@Entity
@Table(name = "shopping_cart", catalog = "Info6250Final")
public class ShoppingCart implements java.io.Serializable {

	private Integer shoppingCartId;
	private IdeaOption ideaOption;
	private User user;
	private Date addedOnDate;

	public ShoppingCart() {
	}

	public ShoppingCart(IdeaOption ideaOption, User user, Date addedOnDate) {
		this.ideaOption = ideaOption;
		this.user = user;
		this.addedOnDate = addedOnDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "shopping_cart_id", unique = true, nullable = false)
	public Integer getShoppingCartId() {
		return this.shoppingCartId;
	}

	public void setShoppingCartId(Integer shoppingCartId) {
		this.shoppingCartId = shoppingCartId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "option_id", nullable = false)
	public IdeaOption getIdeaOption() {
		return this.ideaOption;
	}

	public void setIdeaOption(IdeaOption ideaOption) {
		this.ideaOption = ideaOption;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "added_on_date", nullable = false, length = 19)
	public Date getAddedOnDate() {
		return this.addedOnDate;
	}

	public void setAddedOnDate(Date addedOnDate) {
		this.addedOnDate = addedOnDate;
	}

}
