package neu.edu.temp;
// Generated Nov 28, 2017 3:48:38 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Startup generated by hbm2java
 */
@Entity
@Table(name = "startup", catalog = "Info6250Final")
public class Startup implements java.io.Serializable {

	private int startupId;
	private Category category;
	private Set<BidRecord> bidRecords = new HashSet<BidRecord>(0);

	public Startup() {
	}

	public Startup(int startupId, Category category) {
		this.startupId = startupId;
		this.category = category;
	}

	public Startup(int startupId, Category category, Set<BidRecord> bidRecords) {
		this.startupId = startupId;
		this.category = category;
		this.bidRecords = bidRecords;
	}

	@Id

	@Column(name = "startup_id", unique = true, nullable = false)
	public int getStartupId() {
		return this.startupId;
	}

	public void setStartupId(int startupId) {
		this.startupId = startupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "startup")
	public Set<BidRecord> getBidRecords() {
		return this.bidRecords;
	}

	public void setBidRecords(Set<BidRecord> bidRecords) {
		this.bidRecords = bidRecords;
	}

}
