package neu.edu.entity;
// default package
// Generated Dec 7, 2017 12:18:31 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BidRecord generated by hbm2java
 */
@Entity
@Table(name = "bid_record")
public class BidRecord implements java.io.Serializable {

	private Integer bidId;
	private Startup startup;
	private StartupService startupService;
	private String bidDesc;
	private String bidStatus;
	private Date startDate;
	private Date endDate;
	private float bidAmount;

	public BidRecord() {
	}

	public BidRecord(Startup startup, StartupService startupService, String bidDesc, Date startDate, Date endDate,
			float bidAmount) {
		this.startup = startup;
		this.startupService = startupService;
		this.bidDesc = bidDesc;
		this.startDate = startDate;
		this.endDate = endDate;
		this.bidAmount = bidAmount;
	}

	public BidRecord(Startup startup, StartupService startupService, String bidDesc, String bidStatus, Date startDate,
			Date endDate, float bidAmount) {
		this.startup = startup;
		this.startupService = startupService;
		this.bidDesc = bidDesc;
		this.bidStatus = bidStatus;
		this.startDate = startDate;
		this.endDate = endDate;
		this.bidAmount = bidAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bid_id", unique = true, nullable = false)
	public Integer getBidId() {
		return this.bidId;
	}

	public void setBidId(Integer bidId) {
		this.bidId = bidId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "startup_id", nullable = false)
	public Startup getStartup() {
		return this.startup;
	}

	public void setStartup(Startup startup) {
		this.startup = startup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_id", nullable = false)
	public StartupService getStartupService() {
		return this.startupService;
	}

	public void setStartupService(StartupService startupService) {
		this.startupService = startupService;
	}

	@Column(name = "bid_desc", nullable = false, length = 500)
	public String getBidDesc() {
		return this.bidDesc;
	}

	public void setBidDesc(String bidDesc) {
		this.bidDesc = bidDesc;
	}

	@Column(name = "bid_status", length = 20)
	public String getBidStatus() {
		return this.bidStatus;
	}

	public void setBidStatus(String bidStatus) {
		this.bidStatus = bidStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "bid_amount", nullable = false, precision = 12, scale = 0)
	public float getBidAmount() {
		return this.bidAmount;
	}

	public void setBidAmount(float bidAmount) {
		this.bidAmount = bidAmount;
	}

}
