package neu.edu.entity;
// default package
// Generated Dec 9, 2017 1:25:52 AM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdeaOption generated by hbm2java
 */
@Entity
@Table(name = "idea_option")
public class IdeaOption implements java.io.Serializable {

	private Integer optionId;
	private Idea idea;
	private String optionDesc;
	private float optionPrice;
	private float maxFunding;
	private int boughtAmount;
	private Set<Purchase> purchases = new HashSet<Purchase>(0);
	private Set<ShoppingCart> shoppingCarts = new HashSet<ShoppingCart>(0);

	public IdeaOption() {
	}

	public IdeaOption(Idea idea, float optionPrice, float maxFunding, int boughtAmount) {
		this.idea = idea;
		this.optionPrice = optionPrice;
		this.maxFunding = maxFunding;
		this.boughtAmount = boughtAmount;
	}

	public IdeaOption(Idea idea, String optionDesc, float optionPrice, float maxFunding, int boughtAmount,
			Set<Purchase> purchases, Set<ShoppingCart> shoppingCarts) {
		this.idea = idea;
		this.optionDesc = optionDesc;
		this.optionPrice = optionPrice;
		this.maxFunding = maxFunding;
		this.boughtAmount = boughtAmount;
		this.purchases = purchases;
		this.shoppingCarts = shoppingCarts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "option_id", unique = true, nullable = false)
	public Integer getOptionId() {
		return this.optionId;
	}

	public void setOptionId(Integer optionId) {
		this.optionId = optionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_id", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@Column(name = "option_desc", length = 200)
	public String getOptionDesc() {
		return this.optionDesc;
	}

	public void setOptionDesc(String optionDesc) {
		this.optionDesc = optionDesc;
	}

	@Column(name = "option_price", nullable = false, precision = 12, scale = 0)
	public float getOptionPrice() {
		return this.optionPrice;
	}

	public void setOptionPrice(float optionPrice) {
		this.optionPrice = optionPrice;
	}

	@Column(name = "max_funding", nullable = false, precision = 12, scale = 0)
	public float getMaxFunding() {
		return this.maxFunding;
	}

	public void setMaxFunding(float maxFunding) {
		this.maxFunding = maxFunding;
	}

	@Column(name = "bought_amount", nullable = false)
	public int getBoughtAmount() {
		return this.boughtAmount;
	}

	public void setBoughtAmount(int boughtAmount) {
		this.boughtAmount = boughtAmount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaOption")
	public Set<Purchase> getPurchases() {
		return this.purchases;
	}

	public void setPurchases(Set<Purchase> purchases) {
		this.purchases = purchases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaOption")
	public Set<ShoppingCart> getShoppingCarts() {
		return this.shoppingCarts;
	}

	public void setShoppingCarts(Set<ShoppingCart> shoppingCarts) {
		this.shoppingCarts = shoppingCarts;
	}

}
