package neu.edu.entity;
// default package
// Generated Dec 7, 2017 12:18:31 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Idea generated by hbm2java
 */
@Entity
@Table(name = "idea")
public class Idea implements java.io.Serializable {

	private Integer ideaId;
	private Category category;
	private User user;
	private String ideaName;
	private String ideaDesc;
	private float targetAmount;
	private float gatheredAmount;
	private Date startDate;
	private Date endDate;
	private String ideaStatus;
	private Set<IdeaOption> ideaOptions = new HashSet<IdeaOption>(0);
	private Set<StartupService> startupServices = new HashSet<StartupService>(0);

	public Idea() {
	}

	public Idea(Category category, User user, String ideaName, String ideaDesc, float targetAmount,
			float gatheredAmount, Date startDate, Date endDate, String ideaStatus) {
		this.category = category;
		this.user = user;
		this.ideaName = ideaName;
		this.ideaDesc = ideaDesc;
		this.targetAmount = targetAmount;
		this.gatheredAmount = gatheredAmount;
		this.startDate = startDate;
		this.endDate = endDate;
		this.ideaStatus = ideaStatus;
	}

	public Idea(Category category, User user, String ideaName, String ideaDesc, float targetAmount,
			float gatheredAmount, Date startDate, Date endDate, String ideaStatus, Set<IdeaOption> ideaOptions,
			Set<StartupService> startupServices) {
		this.category = category;
		this.user = user;
		this.ideaName = ideaName;
		this.ideaDesc = ideaDesc;
		this.targetAmount = targetAmount;
		this.gatheredAmount = gatheredAmount;
		this.startDate = startDate;
		this.endDate = endDate;
		this.ideaStatus = ideaStatus;
		this.ideaOptions = ideaOptions;
		this.startupServices = startupServices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idea_id", unique = true, nullable = false)
	public Integer getIdeaId() {
		return this.ideaId;
	}

	public void setIdeaId(Integer ideaId) {
		this.ideaId = ideaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "idea_name", nullable = false, length = 20)
	public String getIdeaName() {
		return this.ideaName;
	}

	public void setIdeaName(String ideaName) {
		this.ideaName = ideaName;
	}

	@Column(name = "idea_desc", nullable = false, length = 400)
	public String getIdeaDesc() {
		return this.ideaDesc;
	}

	public void setIdeaDesc(String ideaDesc) {
		this.ideaDesc = ideaDesc;
	}

	@Column(name = "target_amount", nullable = false, precision = 12, scale = 0)
	public float getTargetAmount() {
		return this.targetAmount;
	}

	public void setTargetAmount(float targetAmount) {
		this.targetAmount = targetAmount;
	}

	@Column(name = "gathered_amount", nullable = false, precision = 12, scale = 0)
	public float getGatheredAmount() {
		return this.gatheredAmount;
	}

	public void setGatheredAmount(float gatheredAmount) {
		this.gatheredAmount = gatheredAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "idea_status", nullable = false, length = 20)
	public String getIdeaStatus() {
		return this.ideaStatus;
	}

	public void setIdeaStatus(String ideaStatus) {
		this.ideaStatus = ideaStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<IdeaOption> getIdeaOptions() {
		return this.ideaOptions;
	}

	public void setIdeaOptions(Set<IdeaOption> ideaOptions) {
		this.ideaOptions = ideaOptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<StartupService> getStartupServices() {
		return this.startupServices;
	}

	public void setStartupServices(Set<StartupService> startupServices) {
		this.startupServices = startupServices;
	}

}
