package neu.edu.entity;
// default package
// Generated Dec 11, 2017 9:21:14 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name = "purchase")
public class Purchase implements java.io.Serializable {

	private Integer purchaseId;
	private IdeaOption ideaOption;
	private User user;
	private int purchaseAmount;
	private Date purchaseDate;
	private String purchaseStatus;

	public Purchase() {
	}

	public Purchase(IdeaOption ideaOption, User user, int purchaseAmount, Date purchaseDate, String purchaseStatus) {
		this.ideaOption = ideaOption;
		this.user = user;
		this.purchaseAmount = purchaseAmount;
		this.purchaseDate = purchaseDate;
		this.purchaseStatus = purchaseStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "purchase_id", unique = true, nullable = false)
	public Integer getPurchaseId() {
		return this.purchaseId;
	}

	public void setPurchaseId(Integer purchaseId) {
		this.purchaseId = purchaseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "option_id", nullable = false)
	public IdeaOption getIdeaOption() {
		return this.ideaOption;
	}

	public void setIdeaOption(IdeaOption ideaOption) {
		this.ideaOption = ideaOption;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "purchase_amount", nullable = false)
	public int getPurchaseAmount() {
		return this.purchaseAmount;
	}

	public void setPurchaseAmount(int purchaseAmount) {
		this.purchaseAmount = purchaseAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "purchase_date", nullable = false, length = 19)
	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	@Column(name = "purchase_status", nullable = false, length = 20)
	public String getPurchaseStatus() {
		return this.purchaseStatus;
	}

	public void setPurchaseStatus(String purchaseStatus) {
		this.purchaseStatus = purchaseStatus;
	}

}
