package neu.edu.entity;
// default package
// Generated Dec 7, 2017 12:18:31 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StartupService generated by hbm2java
 */
@Entity
@Table(name = "startup_service")
public class StartupService implements java.io.Serializable {

	private Integer serviceId;
	private Idea idea;
	private Date startDate;
	private float baseAmount;
	private Date endDate;
	private String serviceDesc;
	private String serviceStatus;
	private Set<CompletionRecord> completionRecords = new HashSet<CompletionRecord>(0);
	private Set<BidRecord> bidRecords = new HashSet<BidRecord>(0);

	public StartupService() {
	}

	public StartupService(Idea idea, Date startDate, float baseAmount, Date endDate) {
		this.idea = idea;
		this.startDate = startDate;
		this.baseAmount = baseAmount;
		this.endDate = endDate;
	}

	public StartupService(Idea idea, Date startDate, float baseAmount, Date endDate, String serviceDesc,
			String serviceStatus, Set<CompletionRecord> completionRecords, Set<BidRecord> bidRecords) {
		this.idea = idea;
		this.startDate = startDate;
		this.baseAmount = baseAmount;
		this.endDate = endDate;
		this.serviceDesc = serviceDesc;
		this.serviceStatus = serviceStatus;
		this.completionRecords = completionRecords;
		this.bidRecords = bidRecords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "service_id", unique = true, nullable = false)
	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_id", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "base_amount", nullable = false, precision = 12, scale = 0)
	public float getBaseAmount() {
		return this.baseAmount;
	}

	public void setBaseAmount(float baseAmount) {
		this.baseAmount = baseAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "service_desc", length = 400)
	public String getServiceDesc() {
		return this.serviceDesc;
	}

	public void setServiceDesc(String serviceDesc) {
		this.serviceDesc = serviceDesc;
	}

	@Column(name = "service_status", length = 20)
	public String getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "startupService")
	public Set<CompletionRecord> getCompletionRecords() {
		return this.completionRecords;
	}

	public void setCompletionRecords(Set<CompletionRecord> completionRecords) {
		this.completionRecords = completionRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "startupService")
	public Set<BidRecord> getBidRecords() {
		return this.bidRecords;
	}

	public void setBidRecords(Set<BidRecord> bidRecords) {
		this.bidRecords = bidRecords;
	}

}
